---

  enable_cloudwatch_agent: true
  enable_unattended_upgrades: true
  unattended_mail: tom.elliott@nyu.edu,alecpm@gmail.com
  unattended_mail_only_on_error: true
  unattended_automatic_reboot: true
  unattended_automatic_reboot_time: 02:00
  unattended_origins_patterns:
    - 'origin=Ubuntu,archive=${distro_codename}-security'
    - 'o=${distro_id},a=${distro_codename}'
    - 'o=${distro_id},a=${distro_codename}-updates'
    - 'o=${distro_id}ESMApps,a=${distro_codename}-apps-security'
    - 'o=${distro_id}ESMApps,a=${distro_codename}-apps-updates'
    - 'o=${distro_id}ESM,a=${distro_codename}-infra-security'
    - 'o=${distro_id}ESM,a=${distro_codename}-infra-updates'
  enable_sitemap: false
  newrelic_license_key: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        30616639656431626432613637666339613134326139396666306533363462353237303765373537
        6338646139353532616637366236666535656436323730380a643838663064396362376631326163
        66366336663936623864363762366332336264653563383836356161363535663139323536323564
        3030366466653931310a393661393564383761336134653633363433323030323262616262626462
        61336565336633666534333463326563376231323834363031323962363262303336653532393338
        6332306565333064626538623833623431653765643036353137
  enable_nrinfra: false
  nrinfragent_config:
    license_key: "{{ newrelic_license_key }}"
    log_file: /var/log/nr-infra.log
    log_to_stdout: false
    nrinfragent_integrations:
      - { name: nri-apache, state: "latest" }
      - { name: nri-varnish, state: "latest" }
      - { name: nri-haproxy, state: "latest" }
    nrinfragent_os_codename: bionic
  nrinfragent_os_codename: bionic
  ansible_selinux: false
  http_port: 80
  max_clients: 200
  proxycache_port: 6081
  proxycache_method: file,/var/lib/varnish/varnish_storage.bin
  proxycache_size: 512m
  haproxy_port: 8081
  cache_preload_urls:
    - /plone
    - /plone/places
  plone_client_base_port: 8401
  plone_client_count: 2
  memmon_limit: 1000MB
  supervisor_tasks:
    - name: pleiades-zeoserver
      command: /srv/python27-apps/pleiades4/bin/zeoserver console
      directory: /srv/python27-apps/pleiades4
      user: plone_daemon
      redirect_stderr: true
      stopwaitsecs: 30
      autostart: true
      autorestart: true

    - name: vtpleiades3
      command:  /srv/python27-apps/vaytrou/bin/vtpython scripts/vtserve -d vtdata pleiades3-three -p 8887
      user: plone_daemon
      directory: /srv/python27-apps/vaytrou
      environment: LD_LIBRARY_PATH="/srv/python27-apps/vaytrou/parts/libgeos/lib:/srv/python27-apps/vaytrou/parts/libspatialindex/lib"
      stopwaitsecs: 30
      stdout_logfile: /srv/python27-apps/vaytrou/vtdata/pleiades3-three/log/vaytrou.log
      stdout_logfile_maxbytes: 50MB
      stderr_logfile: /srv/python27-apps/vaytrou/vtdata/pleiades3-three/log/vaytrou-error.log
      autostart: true
      autorestart: true
  supervisor_events:
    - name: pleiades-memmon
      command: /srv/python27-apps/bin/memmon -a {{memmon_limit}} --name='Pleiades memmon'
      events: TICK_60
      user: root
      stopwaitsecs: 10
      autostart: true
      autorestart: true
  playbook_plones:
    - plone_instance_name: default
      loadbalancer_port: "{{haproxy_port}}"
      plone_client_base_port: 8401
      webserver_virtualhosts:
        - host: default
          plone_path: /plone
  pleiades_buildout_file: staging.cfg
  pleiades_static_branch: master
  pleiades_buildout_branch: master
  vaytrou_branch: pypi-updates
  enable_backups: false

  pleiades_ssl_vhost: off
  pleiades_cert_file: /etc/letsencrypt/live/{{ pleiades_ssl_vhost }}/cert.pem
  pleiades_key_file: /etc/letsencrypt/live/{{ pleiades_ssl_vhost }}/privkey.pem
  pleiades_chained_file: /etc/letsencrypt/live/{{ pleiades_ssl_vhost }}/fullchain.pem

  certbot_account_email: alecpm@gmail.com

  # Apache defaults
  apache_create_vhosts: false
  apache_remove_default_vhost: true
  apache_global_vhost_settings: |
    index.html index.htm
  apache_mods_enabled:
    - alias.load
    - alias.conf
    - auth_basic.load
    - authn_file.load
    - authz_core.load
    - authz_groupfile.load
    - authz_host.load
    - authz_user.load
    - autoindex.load
    - autoindex.conf
    - cgid.load
    - deflate.load
    - deflate.conf
    - dir.load
    - dir.conf
    - env.load
    - expires.load
    - headers.load
    - mime.load
    - mime.conf
    - negotiation.load
    - negotiation.conf
    - proxy.load
    - proxy.conf
    - proxy_connect.load
    - proxy_http.load
    - remoteip.load
    - rewrite.load
    - setenvif.load
    - setenvif.conf
    - status.load
    - status.conf
    - ssl.load
  apache_mods_disabled:
    - evasive.load
    - evasive.conf
  apache_packages:
    - apache2
    - apache2-utils
    - apache2-dev
    - libapache2-mod-wsgi
    - libapache2-mod-svn
    - libapache2-mod-evasive
  apache_ignore_missing_ssl_certificate: true
  install_fail2ban: true

  fail2ban_filterd_path: "{{ playbook_dir }}/files/fail2ban/filter.d/" # Trailing slash is important!

  fail2ban_ignoreips:
    - 127.0.0.1/8
    - ::1
    - 216.240.59.58/32

  fail2ban_services:
    - name: sshd
      enabled: true
      mode: normal
    - name: apache-overflows
      enabled: true
      filter: apache-overflows
      logpath: /var/log/apache2/pleiades.stoa.org-error.log
      port: http,https
      maxretry: 2
    - name: apache-noscript
      filter: apache-noscript
      enabled: true
      logpath: /var/log/apache2/pleiades.stoa.org-error.log
      port: http,https
      maxretry: 2
    - name: apache-blocked
      filter: apache-blocked
      enabled: true
      logpath: /var/log/apache2/pleiades.stoa.org-error.log
      findtime: "30m"
      port: http,https
      maxretry: 2
    - name: apache-badbots
      filter: apache-badbots
      enabled: true
      logpath: /var/log/apache2/pleiades.stoa.org-access.log
      port: http,https
      maxretry: 4
    - name: apache-unauth
      filter: apache-unauth
      enabled: true
      logpath: /var/log/apache2/pleiades.stoa.org-access.log
      port: http,https
      findtime: "30m"
      bantime: "1h"
      maxretry: 2
    - name: plone-logins
      filter: apache-loginbots
      enabled: true
      logpath: /var/log/apache2/pleiades.stoa.org-access.log
      port: http,https
      findtime: "5m"
      maxretry: 5

  anubis_port: 8923
  anubis_difficulty: 4
  anubis_policy_file: /etc/anubis/pleiades.yaml
