---

  newrelic_license_key: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        30616639656431626432613637666339613134326139396666306533363462353237303765373537
        6338646139353532616637366236666535656436323730380a643838663064396362376631326163
        66366336663936623864363762366332336264653563383836356161363535663139323536323564
        3030366466653931310a393661393564383761336134653633363433323030323262616262626462
        61336565336633666534333463326563376231323834363031323962363262303336653532393338
        6332306565333064626538623833623431653765643036353137
  ansible_selinux: false
  http_port: 80
  max_clients: 200
  proxycache_port: 6081
  proxycache_method: file,/var/lib/varnish/varnish_storage.bin
  proxycache_size: 512m
  haproxy_port: 8081
  cache_preload_urls:
    - /plone
    - /plone/places
  plone_client_base_port: 8401
  supervisor_tasks:
    - name: pleiades-zeoserver
      command: /srv/python27-apps/pleiades4/bin/zeoserver console
      directory: /srv/python27-apps/pleiades4
      user: plone_daemon
      redirect_stderr: true
      stopwaitsecs: 30
      autostart: true
      autorestart: true

    - name: vtpleiades3
      command:  /srv/python27-apps/vaytrou/bin/vtpython scripts/vtserve -d vtdata pleiades3-three -p 8887
      user: plone_daemon
      directory: /srv/python27-apps/vaytrou
      environment: LD_LIBRARY_PATH="/srv/python27-apps/vaytrou/parts/libgeos/lib:/srv/python27-apps/vaytrou/parts/libspatialindex/lib"
      stopwaitsecs: 30
      stdout_logfile: /srv/python27-apps/vaytrou/vtdata/pleiades3-three/log/vaytrou.log
      stdout_logfile_maxbytes: 50MB
      stderr_logfile: /srv/python27-apps/vaytrou/vtdata/pleiades3-three/log/vaytrou-error.log
      autostart: true
      autorestart: true
  playbook_plones:
    - plone_instance_name: default
      loadbalancer_port: "{{haproxy_port}}"
      plone_client_base_port: 8401
      webserver_virtualhosts:
        - host: default
          plone_path: /plone
  pleiades_buildout_file: staging.cfg

  letsencrypt_default_key_group: ssl-cert
  letsencrypt_default_key_permissions: 640
  acme_tiny_challenges_directory: /var/www/pleiades.stoa.org/.well-known/acme-challenge/
  acme_tiny_commit: daba51d37efd7c1f205f9da383b9b09968e30d29

