---

- include: "{{ ansible_os_family }}.yml"

- name: Enable selinux boolean haproxy_connect_any
  when: ansible_selinux
  seboolean: name=haproxy_connect_any state=yes persistent=yes

- name: haproxy config
  template:
    src=haproxy.cfg.j2
    dest=/etc/haproxy/haproxy.cfg
    owner=root
    group=root
    mode=644
    backup=true

- name: haproxy started
  service: name=haproxy state=started

- name: reload haproxy
  service: name=haproxy state=reloaded
