---

- hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: no

  vars:
    management_user_list:
      - name: alecpm
        shell: /bin/bash
        createhome: yes
        groups:
          - plone_group
        sudo:
          hosts: ALL
          as: ALL
          commands: ALL
          nopasswd: yes
        authorized_keys:
          - key: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEA1Wp63G60D9rNG+iu301OEjYcBIGcPzwA6eGCmQoizAhc8eHx27YOxlkNPlZ6pdensAft9A2Gd/0bdg5rNtf9XmxPbWmY3LMyat0UafJNX/r4z4x5zqdlnEVdXykXbhmfZta4/ESNMwF4i03wjy+9+EOcdfRswBg1Hc1jXrLlJy0= alec@alec
      - name: dglick
        shell: /bin/bash
        createhome: yes
        groups:
          - plone_group
        sudo:
          hosts: ALL
          as: ALL
          commands: ALL
          nopasswd: yes
        authorized_keys:
          - key: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvciaA3+R2TvROzVNlhAh/XI5jtzu2Y9sX4K6tYBJ+CqjPFAGuz7q71EyUgtXn+7UvHbwwjFXQpKCYcrC2RsNzdoWTyMjgAEXot8YJW2lLBM54whljvUvjGhPGuFpOlvFyvgqP0KbyifR3MAKRmlJuqoTgFTXq8rt0g4yyokyMCSqf1WVBCR6AqIK97GjTqr7Ib2DMQVA+HWp/mdfKvFSVQtZxbkWnGVz1N/iTnNhQ2qEhSFLsBL1AW5kLjKmOTTUhJY0Y+H3ykVjYF3LwyBQUXfq8BQ4KGX/holG9Eg4Ouq+Qpd8ku+rgFv1xHh6EQ7YoDMblcWMV1YG+SYYnrjhlQ== dglick@gmail.com
      - name: thomase
        shell: /bin/bash
        createhome: yes
        groups:
          - plone_group
        sudo:
          hosts: ALL
          as: ALL
          commands: ALL
          nopasswd: yes
        authorized_keys:
          - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0rhT70jvNCeEf/JAACFFDjvLc4jzH16Td4FjiT8zvvFh8GqFKhLkeKdRtEeC69aZNWaYe+ugMeYr7faTeRHLA9ZnRPvscui7hU8qbQi4hRTt0JaB3A8stT1stcaPFJRr09vHYhQAMiuE1CG7GJHILd44W/6zKjw0+8rwUR8Vfj5EOrbVu9wOztfHCtriN1W5EiN1QoF6x2RXlJuLOqlgm9dr5XM1T+caIYl0LndzJkKQtypwEJzgNe9foVzICAKwWA5pJstqviWyaV8Z1g25JRzPAuSO2vYZe1WH37edGJPzPYxVH5u8Hi+aXfvDdIBxnB9ZoisHkV6fVQgm/wMdh tom.elliott@nyu.edu
      - name: cguardia
        shell: /bin/bash
        createhome: yes
        groups:
          - plone_group
        sudo:
          hosts: ALL
          as: ALL
          commands: ALL
          nopasswd: yes
        authorized_keys:
          - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCw9LYyIRaLlaUk3eBvEYxf4JBfSS6gQpngDds2+4rHZ83OmwEFkfbEiNJWInqxGegYEj5M8Z3tkWqJ6N7Cc0ORgYTYpdCrZOkD/IcO8OFqrS5oZCvU0E+UuTbXP+q8JsOYDNRO4cenrDSeB02bP9tRYS4EAhbEH/BkS9FD+zOl8dFYR9cj46FTSCauet2fEvySrypawq44ZkUvDpCMDUTzdxOCIne8kybOX9XS+gooZNiU2Id3m8qz2xrWJUmGXsudlLmPcRavVXeHRlA/5eCcmlyV9QHn/cK86jCkT0nmKnfLqRdq0SQT3s9k9gJPTyBNfRG8v5ya4t+dzAJhXRL9 cguardia@yahoo.com
      - name: witekdev
        shell: /bin/bash
        createhome: yes
        groups:
          - plone_group
        sudo:
          hosts: ALL
          as: ALL
          commands: ALL
          nopasswd: yes
        authorized_keys:
          - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/4N5ov8HMUcHDlRefr3C8PuAQxVpvRs/V0tGnPJn+BV7YzPnmHJyKwjmROMphsCppEv5Lc33qsEoMOwNfPRz3IWLpB4vBwwq9nyvvq67YwClevZPL4O7/gBrqPAmiLIvhOEGNWn1VCDsBHWDN7y1511JZagaLYslv+t5U6+xFIJBdz7kT4ZcXjGx0oawF7ErybYBrIcQbEHcunyPAobM0l/JENV8MiDjsHZ+yQuoHwUQy6YuAelK4uosG+a2GdXxWVxXF0coDyMj43/9dcwY//HnEozlvLBsAO5TOptGuiPMg6NJPnSIzq3sVpDpv9T7UQbukV0Fwa83p+px0xlC5 witekdev@gmail.com

  pre_tasks:
    - name: Ensure plone_group
      group: name=plone_group

  roles:
    - GROG.management-user

  tasks:
    - name: Ensure plone_daemon
      user:
        name=plone_daemon
        group=plone_group
        shell=/bin/bash
        createhome=yes
        generate_ssh_key=yes

    - name: Ensure plone_buildout
      user:
        name=plone_buildout
        group=plone_group
