---

- hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes

  vars:
    management_user_list:
      - name: alecpm
        shell: /bin/bash
        createhome: yes
        groups:
          - plone_group
          - sudo
        sudo:
          hosts: ALL
          as: ALL
          commands: ALL
          nopasswd: yes
        authorized_keys:
          - key: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEA1Wp63G60D9rNG+iu301OEjYcBIGcPzwA6eGCmQoizAhc8eHx27YOxlkNPlZ6pdensAft9A2Gd/0bdg5rNtf9XmxPbWmY3LMyat0UafJNX/r4z4x5zqdlnEVdXykXbhmfZta4/ESNMwF4i03wjy+9+EOcdfRswBg1Hc1jXrLlJy0= alec@alec
      - name: thomase
        shell: /bin/bash
        createhome: yes
        groups:
          - plone_group
          - sudo
        sudo:
          hosts: ALL
          as: ALL
          commands: ALL
          nopasswd: yes
        authorized_keys:
          - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0rhT70jvNCeEf/JAACFFDjvLc4jzH16Td4FjiT8zvvFh8GqFKhLkeKdRtEeC69aZNWaYe+ugMeYr7faTeRHLA9ZnRPvscui7hU8qbQi4hRTt0JaB3A8stT1stcaPFJRr09vHYhQAMiuE1CG7GJHILd44W/6zKjw0+8rwUR8Vfj5EOrbVu9wOztfHCtriN1W5EiN1QoF6x2RXlJuLOqlgm9dr5XM1T+caIYl0LndzJkKQtypwEJzgNe9foVzICAKwWA5pJstqviWyaV8Z1g25JRzPAuSO2vYZe1WH37edGJPzPYxVH5u8Hi+aXfvDdIBxnB9ZoisHkV6fVQgm/wMdh tom.elliott@nyu.edu
      - name: cguardia
        shell: /bin/bash
        createhome: yes
        groups:
          - plone_group
          - sudo
        sudo:
          hosts: ALL
          as: ALL
          commands: ALL
          nopasswd: yes
        authorized_keys:
          - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCw9LYyIRaLlaUk3eBvEYxf4JBfSS6gQpngDds2+4rHZ83OmwEFkfbEiNJWInqxGegYEj5M8Z3tkWqJ6N7Cc0ORgYTYpdCrZOkD/IcO8OFqrS5oZCvU0E+UuTbXP+q8JsOYDNRO4cenrDSeB02bP9tRYS4EAhbEH/BkS9FD+zOl8dFYR9cj46FTSCauet2fEvySrypawq44ZkUvDpCMDUTzdxOCIne8kybOX9XS+gooZNiU2Id3m8qz2xrWJUmGXsudlLmPcRavVXeHRlA/5eCcmlyV9QHn/cK86jCkT0nmKnfLqRdq0SQT3s9k9gJPTyBNfRG8v5ya4t+dzAJhXRL9 cguardia@yahoo.com
      - name: witekdev
        shell: /bin/bash
        createhome: yes
        groups:
          - plone_group
          - sudo
        sudo:
          hosts: ALL
          as: ALL
          commands: ALL
          nopasswd: yes
        authorized_keys:
          - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/4N5ov8HMUcHDlRefr3C8PuAQxVpvRs/V0tGnPJn+BV7YzPnmHJyKwjmROMphsCppEv5Lc33qsEoMOwNfPRz3IWLpB4vBwwq9nyvvq67YwClevZPL4O7/gBrqPAmiLIvhOEGNWn1VCDsBHWDN7y1511JZagaLYslv+t5U6+xFIJBdz7kT4ZcXjGx0oawF7ErybYBrIcQbEHcunyPAobM0l/JENV8MiDjsHZ+yQuoHwUQy6YuAelK4uosG+a2GdXxWVxXF0coDyMj43/9dcwY//HnEozlvLBsAO5TOptGuiPMg6NJPnSIzq3sVpDpv9T7UQbukV0Fwa83p+px0xlC5 witekdev@gmail.com
      - name: mwilkes
        shell: /bin/bash
        createhome: yes
        groups:
          - plone_group
          - sudo
        sudo:
          hosts: ALL
          as: ALL
          commands: ALL
          nopasswd: yes
        authorized_keys:
          - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBeJ2mlhv9u4HU33yMa7Vp5G9prfAGUfTi66pga0PeqMpo71f1aWUV2S5QKN2jCmmrT82Y9waT9IMc+dG2kKhYy4FS3qkaETfEg/+Tr2qqzMUZom5JgMZjY/8XBToqFpE27J2pArkWdHFtxttAWGKFG5humdIoKK4HLMXgWiTX8tUo6h1lc9WBX9dqWt3YGhJas6vBr2cO3/C/guG2qBRZy+WIShSbgF8qL/fToAhajqQe3k5+LbYfJkIClJYMTsArGHdHBAf1mLhWWu0Y+xsO3SfR0+1quLEL9OZvpvAVY11/4AJimoRH7vhS7RDrd1ChO7S8UK2ylQJ2BrC92euv matthewwilkes@jazkarta

  pre_tasks:
    - name: Ensure plone_group
      group: name=plone_group

  roles:
    - GROG.management-user

  tasks:
    - name: Ensure plone_daemon
      user:
        name=plone_daemon
        group=plone_group
        shell=/bin/bash
        createhome=yes
        generate_ssh_key=yes

    - name: Ensure plone_buildout
      user:
        name=plone_buildout
        group=plone_group
