---

- hosts: all
  sudo: yes
  gather_facts: no

  tasks:

  - name: Install ufw
    apt: pkg=ufw
  - name: Enable ufw
    ufw: state=enabled policy=allow
  - name: Disable default in
    ufw: direction=incoming policy=deny
  - name: Allow ssh in
    ufw: rule=allow name=OpenSSH
  - name: 80 is open
    ufw: rule=allow port=80 proto=tcp
  - name: 443 is open
    ufw: rule=allow port=443 proto=tcp
  - name: 8080 is open
    ufw: rule=allow port=8080 proto=tcp
