---
- hosts: all
  vars:
    newrelic_service_state: started
    meetme_newrelic_plugin_agent_template: templates/newrelic-plugin-agent.yml.j2
  become: true
  become_user: root
  become_method: sudo

  pre_tasks:
    - name: Install required packages
      apt:
        state: present
        pkg: 
          - build-essential
          - python2-dev
          - default-jre
          - nodejs

  roles:
    - role: weareinteractive.newrelic
    - role: newrelic.newrelic-infra
      vars:
        nrinfragent_os_codename: bionic
      when: enable_nrinfra
