---

- hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:

    - name: Gather service facts
      ansible.builtin.service_facts:
      tags:
        - insightvm

    - name: Set fact if ir_agent service is running
      set_fact:
        ir_agent_exists: true
      when:
        - "'ir_agent.service' in ansible_facts.services"

    - name: Set fact if ir_agent service is not running
      set_fact:
        ir_agent_exists: false
      when: ir_agent_exists is not defined

    - name: Check that the InsightVM tools exist
      stat:
        path: /opt/rapid7/ir_agent/ir_agent
      register: ir_agent_stat
      tags:
        - insightvm

    - name: Upload InsightVM Files
      ansible.builtin.copy:
        src: files/insightvm
        dest: /var/lib
        owner: root
        group: root
        mode: "0700"
        force: false
      when: not ir_agent_exists
      tags:
        - insightvm

    - name: Install InsightVM package
      apt:
        deb: /var/lib/insightvm/rapid7-insight-agent_4.0.15.31-1_arm64.deb
        state: present
      when: not ir_agent_exists
      tags:
        - insightvm

    - name: Configure and enable agent
      ansible.builtin.command:
        cmd: /opt/rapid7/ir_agent/components/insight_agent/4.0.18.46/configure_agent.sh --certificate_package_installation=/var/lib/insightvm -v --attributes="ISAW" --start
      when: not ir_agent_exists
      tags:
        - insightvm

    - name: Create cortex config directory
      ansible.builtin.file:
        path: /etc/panw
        state: directory
        owner: root
        group: root
        mode: "0700"
      tags:
        - cortex

    - name: Install Cortex config
      ansible.builtin.copy:
        src: files/cortex/cortex.conf
        dest: /etc/panw/
        owner: root
        group: root
        mode: "0700"
      tags:
        - cortex

    - name: Check that the cytool exists
      stat:
        path: /opt/traps/bin/cytool
      register: cytool_stat
      tags:
        - cortex

    - name: Upload Cortex installer to tmp dir
      ansible.builtin.copy:
        src: files/cortex/cortex-8.7.0.131661.deb
        dest: /tmp/
        owner: root
        group: root
        mode: "0700"
      when: not cytool_stat.stat.exists
      tags:
        - cortex

    - name: Install cortex
      ansible.builtin.apt:
        deb: /tmp/cortex-8.7.0.131661.deb
        state: present
      when: not cytool_stat.stat.exists
      tags:
        - cortex

    - name: Remove cortex installer
      ansible.builtin.file:
        path: /tmp/cortex-8.7.0.131661.deb
        state: absent
      tags:
        - cortex
