#! /bin/sh

# pleiades-sitemap

set -e

PLEIADES_HOME=/srv/python27-apps/pleiades4/

# Run sitemapping script as zope user
cd $PLEIADES_HOME
# . ./setenv
su plone_buildout -c "./bin/debug-instance run src/pleiades.sitemap/pleiades/sitemap/writer.py -d /tmp/ -z"

# Copy sitemaps to pleiades.stoa.org
cd /var/www/pleiades.stoa.org
cp /tmp/sitemap* .
chown www-data.www-data sitemap*
chmod 644 sitemap*

