#! /bin/sh

# pleiades-json

# set -e

PLEIADES_HOME=/srv/python27-apps/pleiades4/
DEST=/var/www/atlantides.org/downloads/pleiades/json

# Run sitemapping script as zope user
cd $PLEIADES_HOME
su plone_daemon -c "./bin/debug-instance -Oplone run src/Products.PleiadesEntity/Products/PleiadesEntity/commands/dump.py $DEST" 2> dump.log
